

# Project information
site_name: Shape Up - راهکاری برای مدیریت و طراحی محصول نرم‌افزاری
site_url: https://neveshteh.net/shapeup/
site_author: محمد تکلو
site_description: >-
  ترجمه فارسی کتاب Shape Up، راهکاری برای مدیریت و طراحی محصول نرم‌افزاری


# Copyright
copyright: حق نشر متن اصلی متعلق به 37signals/Basecamp است. ترجمه فارسی توسط محمد تکلو منتشر شده است.

# Configuration
theme:
  name: 'material'


  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: 'fa'
  direction: 'rtl'
  # features:
  #   - tabs
    #- instant
  palette:
    scheme: default
    primary: black
    accent: white
  font:
    text: false
    
  icon:
    logo: logo
  favicon: assets/favicon.png

# Plugins
plugins:
  - search
extra_css:
  - 'stylesheets/extra.css'
# Customization
extra:
  social:
    - icon: fontawesome/regular/envelope
      link: mailto:smt.takalloo@gmail.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/SmtTakalloo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mohamad-takalloo-a84764134/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/takalloo.mohamad


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
- صفحه اصلی: 'index.md'
- مقدمه:
    - مقدمه مترجم: 'abstraction/translate_abstract.md'
    - پیش‌گفتار: 'preface/foreword.md'
    - سپاسگزاری‌ها: 'preface/acknowledgements.md'
    - مقدمه نویسنده: 'abstraction/abstraction.md'
- بخش اول - شیپینگ:
    - اصول شیپینگ: 'partone/principles_of_shaping.md'
    - تعیین مرزها: 'partone/set_boundaries.md'
    - پیدا کردن عناصر: 'partone/find_the_elements.md'
    - ریسک‌ها و حفره‌های خرگوش: 'partone/risks_and_rabbit_holes.md'
    - نوشتن پیچ: 'partone/write_the_pitch.md'
- بخش دوم - شرط‌بندی:
    - شرط‌بندی، نه بک‌لاگ: 'parttwo/bets_not_backlogs.md'
    - میز شرط‌بندی: 'parttwo/the_betting_table.md'
    - شرط‌های خود را بگذارید: 'parttwo/place_your_bets.md'
- بخش سوم - ساختن:
    - واگذاری مسئولیت: 'partthree/hand_over_responsibility.md'
    - یک بخش را کامل کنید: 'partthree/get_one_piece_done.md'
    - نقشه‌برداری از اسکوپ‌ها: 'partthree/map_the_scopes.md'
    - نشان دادن پیشرفت: 'partthree/show_progress.md'
    - تصمیم گرفتن درباره زمان توقف: 'partthree/decide_when_to_stop.md'
    - عبور کنید: 'partthree/move_on.md'
    - نتیجه‌گیری: 'partthree/conclusion.md'
- پیوست‌ها:
    - اجرای شیپ‌آپ در بیس‌کمپ: 'appendices/implement_shapeup_in_basecamp.md'
    - متناسب با اندازه خودتان تنظیم کنید: 'appendices/adjust_to_your_size.md'
    - چگونه شیپ‌آپ را شروع کنیم: 'appendices/how_to_begin.md'
    - واژه‌نامه: 'appendices/glossary.md'
    - درباره نویسنده: 'appendices/about_author.md'
